services:
    app:
        build:
            context: .
        container_name: cart-service
        restart: unless-stopped
        working_dir: /var/www
        user: "1000:1000"
        volumes:
            - ./:/var/www
        depends_on:
            - db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        expose:
            - "9000"

    nginx:
        image: nginx:1.25
        container_name: cart-web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: postgres:15
        container_name: cart-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:

networks:
    default:
        name: net_bussola
