services:
    app:
        build:
            context: .
            args:
                NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
                NEW_RELIC_APPNAME: CartService-Laravel
        container_name: cart-service
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.docker/php-docker.ini:/usr/local/etc/php/conf.d/newrelic.ini:ro
        depends_on:
            - db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
            NEW_RELIC_APP_NAME: CartService-Laravel
        expose:
            - "9000"
        networks:
            - net_project

    nginx:
        image: nginx:1.25
        container_name: cart-web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./storage/nginx/logs:/var/log/nginx
        depends_on:
            - app
        networks:
            - net_project

    db:
        image: postgres:15
        container_name: cart-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - net_project

    newrelic-infra:
        image: newrelic/infrastructure:latest
        container_name: cart-nr-infra
        restart: always
        privileged: true
        network_mode: host
        cap_add:
            - SYS_PTRACE
        environment:
            - NRIA_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
            - NRIA_DISPLAY_NAME=cart-service
            - NRIA_OVERRIDE_HOST_ROOT=/host
            - PG_HOST=db
            - PG_PORT=5432
            - PG_USER=${POSTGRES_USER}
            - PG_PASSWORD=${POSTGRES_PASSWORD}
            - PG_DATABASE=${POSTGRES_DB}
            - NGINX_SERVICE=cart
        volumes:
            - /:/host:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - ./storage/nginx/logs:/var/log/nginx:ro
            - ./.docker/newrelic-integrations.yaml:/etc/newrelic-infra/integrations.d/postgresql-config.yaml:ro
            - ./.docker/newrelic-logs.yml:/etc/newrelic-infra/logging.d/nginx.yml:ro

volumes:
    pgdata:

networks:
    net_project:
        name: net_bussola
        driver: bridge
